/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Payroll.java
 *
 * Created on Dec 14, 2011, 9:56:42 AM
 */

package payrollsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wycliffe
 */
public class Payroll extends javax.swing.JFrame
{
    ResultSet resultset,rs,rs1,rs2;
    Statement statement,statement2;
    ResultSetMetaData ram;
    String sql = "select * from employees";
    String sql2 = "select sum(BasicSalary) from employees";
    String sql3 = "select sum(Tax) from employees";
    String sql4 = "select sum(NetSalary) from employees";
    String empid,gender,firstName,surname,accountNumber,empType,dateOfHire,basicSal1,netSal1,netTax1,NetSal1;//declares the vairiables for the table viewing
    int basicSal,i=0;
    double netSal,netTax;
    /** Creates new form Payroll */
    public Payroll() {
        initComponents();
        try
        {
           Class.forName("com.mysql.jdbc.Driver");
           System.out.println("Driver Loaded");
           Connection connection  = DriverManager.getConnection("jdbc:mysql://localhost/payroll");
           System.out.println("Database connected");
           statement = connection.createStatement(resultset.TYPE_SCROLL_SENSITIVE,resultset.CONCUR_UPDATABLE );
           resultset = statement.executeQuery(sql);
           System.out.print("Querry is executed\n");
           
            DefaultTableModel model=(DefaultTableModel) jtblViewEmp.getModel();
       try
       {
       model.setNumRows(0);
       for(int i=model.getRowCount()-1;1>=0;i++)
	{
           resultset.insertRow();
        }
        }
        catch(ArrayIndexOutOfBoundsException e)
        {
         //JOptionPane.showConfirmDialog(null,"continue","click any button to continue",JOptionPane.DEFAULT_OPTION);
        }
        catch(SQLException e)
        {
         //JOptionPane.showConfirmDialog(null,"continue","click any button to continue",JOptionPane.DEFAULT_OPTION);
        }
        try
	{
            resultset = statement.executeQuery(sql);

            while(resultset.next())
            {
                firstName = (resultset.getString(5));
                surname =(resultset.getString(4));
                empid =(resultset.getString(1));
                gender = (resultset.getString(6));
                accountNumber = (resultset.getString(3));
                basicSal1 = (resultset.getString(12));
                basicSal = Integer.parseInt(basicSal1);
                netTax1 = (resultset.getString(16));
                netTax = Double.parseDouble(netTax1);
                NetSal1 = (resultset.getString(17));
                netSal = Double.parseDouble(NetSal1);
                
                empType = (resultset.getString(22));
                model.addRow(new Object[]{firstName,surname,empid,gender,accountNumber,basicSal,netTax1,netSal});

               

                 String in = resultset.getString(12);
                 System.out.print(in);
                 double bs = Double.parseDouble(in);
                 double bs1 = bs++;
                 jtxtTotalBasic.setText(String.format("%.2f",bs1));
                
            
            }
        }
	catch (SQLException ex)
	{
            Logger.getLogger(PayrollEmployeeDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        catch(SQLException e)
        {
        }
        catch(ClassNotFoundException cl)
        {
        }
        try
        {
          rs = statement.executeQuery("select sum(BasicSalary) from employees");
          rs1 = statement.executeQuery(sql3);
          rs2 = statement.executeQuery(sql4);

          jtxtTotalBasic.setText(rs.getString("sum(BasicSalary)"));
          jtxtTotalTax.setText(rs1.getString(1));
          jtxtTotalNetTax.setText(rs2.getString(1));
        }
        catch(SQLException e)
        {

        }
        try
        {
        if(resultset.next())
        {
            String in = resultset.getString(12);
            System.out.print(in);
            double bs = Double.parseDouble(in);
            double bs1 = bs++;
            jtxtTotalBasic.setText(in);
        }
        }
        catch(SQLException e)
        {

        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelHome = new javax.swing.JPanel();
        jLabelTitleHome = new javax.swing.JLabel();
        jPanelDesignBar = new javax.swing.JPanel();
        jlblLogo = new javax.swing.JLabel();
        jblLogo2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblViewEmp = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotalTax = new javax.swing.JTextField();
        jtxtTotalNetTax = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtTotalBasic = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Wybosoft University College Payroll ");

        jPanelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTitleHome.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelTitleHome.setForeground(new java.awt.Color(51, 0, 255));
        jLabelTitleHome.setText("Wybosoft University College ");
        jLabelTitleHome.setToolTipText(" Wybosoft inc. Login");

        jPanelDesignBar.setBackground(new java.awt.Color(51, 0, 255));
        jPanelDesignBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelDesignBarLayout = new javax.swing.GroupLayout(jPanelDesignBar);
        jPanelDesignBar.setLayout(jPanelDesignBarLayout);
        jPanelDesignBarLayout.setHorizontalGroup(
            jPanelDesignBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );
        jPanelDesignBarLayout.setVerticalGroup(
            jPanelDesignBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jlblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/ICO/wybosoft.gif"))); // NOI18N

        jblLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/ICO/wybosoft.gif"))); // NOI18N

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addComponent(jlblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jPanelDesignBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jLabelTitleHome)
                        .addGap(118, 118, 118)))
                .addComponent(jblLogo2))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitleHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelDesignBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jlblLogo)
                    .addComponent(jblLogo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1286, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jtblViewEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Employee Surname", "Gender", "Account Number", "Basic Salary", "Net Tax", "Net Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblViewEmp.setColumnSelectionAllowed(true);
        jtblViewEmp.setEnabled(false);
        jtblViewEmp.setRowHeight(20);
        jtblViewEmp.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtblViewEmp);
        jtblViewEmp.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Total Tax ");

        jtxtTotalTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalTaxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Total Net Salary");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Total Basic Salary");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtTotalBasic, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jtxtTotalTax)
                    .addComponent(jtxtTotalNetTax))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTotalBasic, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTotalTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jtxtTotalNetTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(104, 104, 104))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(591, 591, 591)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtTotalTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalTaxActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelTitleHome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDesignBar;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblLogo2;
    private javax.swing.JLabel jlblLogo;
    private javax.swing.JTable jtblViewEmp;
    private javax.swing.JTextField jtxtTotalBasic;
    private javax.swing.JTextField jtxtTotalNetTax;
    private javax.swing.JTextField jtxtTotalTax;
    // End of variables declaration//GEN-END:variables

}
