/*This is payroll system. The program is intened to help ease the production of
payslips and the payroll of the wybosoft organisation. It is also supposed to register new
departments and also new employee through appropriate interface.
 */
/*@author Wycliffe
 */
package payrollsystem;

public class PayrollHome extends javax.swing.JFrame {

    /** Creates new form PayrollHome */
    public PayrollHome() {
        initComponents();
        jInternalFrame1.setTitle("Wybosoft University College");
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel7 = new javax.swing.JLabel();
        jPanelHome = new javax.swing.JPanel();
        jLabelTitleHome = new javax.swing.JLabel();
        jPanelDesignBar = new javax.swing.JPanel();
        jblLogo2 = new javax.swing.JLabel();
        jlblLogo = new javax.swing.JLabel();
        jlblMotto = new javax.swing.JLabel();
        jMenuBarHome = new javax.swing.JMenuBar();
        jmnuAdmin = new javax.swing.JMenu();
        jmnuPaymnts = new javax.swing.JMenu();
        jmnuItemPaySlip = new javax.swing.JMenuItem();
        jMenuItemPayroll = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmnuAllParmnt = new javax.swing.JMenuItem();
        jmnuAllCntrct = new javax.swing.JMenuItem();
        jmnuAllCasual = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmnuItemAddNewDept1 = new javax.swing.JMenuItem();
        jmnuItemAddNewEmployee = new javax.swing.JMenuItem();
        jmnuItemAddNewBankDetails = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmnuExit = new javax.swing.JMenuItem();
        jmnuDepartment = new javax.swing.JMenu();
        jMenuFinance = new javax.swing.JMenu();
        jmnuFinParm = new javax.swing.JMenuItem();
        jmnuFinContract = new javax.swing.JMenuItem();
        jmnuFinCasual = new javax.swing.JMenuItem();
        jmnuHR = new javax.swing.JMenuItem();
        jmnuExam = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmnuCit = new javax.swing.JMenuItem();
        jmnuBEC = new javax.swing.JMenuItem();
        jmnuTaxMgt = new javax.swing.JMenu();
        jmnuNetTaxPerMonth = new javax.swing.JMenuItem();
        jmnuHome = new javax.swing.JMenu();
        jmnuHomeHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("Wybosoft Payroll System_2011");
        jInternalFrame1.setToolTipText("Wybosoft University College Home Interfac");
        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Welcome to home interface of ");

        jToolBar1.setBackground(new java.awt.Color(204, 0, 0));
        jToolBar1.setRollover(true);

        jLabel7.setBackground(new java.awt.Color(204, 0, 0));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("Wybosoft University College...A completely integreted Payroll system                                           P.O Box 2222-60999, Nairobi-Kenya; E-Mail  Wybosoft@education.edu.ke");
        jLabel7.setToolTipText("Bank Payment details");

        jPanelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTitleHome.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelTitleHome.setForeground(new java.awt.Color(51, 0, 255));
        jLabelTitleHome.setText("Wybosoft University College ");
        jLabelTitleHome.setToolTipText(" Wybosoft inc. Login");

        jPanelDesignBar.setBackground(new java.awt.Color(51, 0, 255));
        jPanelDesignBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelDesignBarLayout = new javax.swing.GroupLayout(jPanelDesignBar);
        jPanelDesignBar.setLayout(jPanelDesignBarLayout);
        jPanelDesignBarLayout.setHorizontalGroup(
            jPanelDesignBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );
        jPanelDesignBarLayout.setVerticalGroup(
            jPanelDesignBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jblLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/ICO/wybosoft.gif"))); // NOI18N

        jlblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/ICO/wybosoft.gif"))); // NOI18N

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addComponent(jlblLogo)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelDesignBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabelTitleHome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblLogo2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitleHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelDesignBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jlblLogo)
                    .addComponent(jblLogo2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap())
        );

        jlblMotto.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jlblMotto.setForeground(new java.awt.Color(204, 0, 0));
        jlblMotto.setText("Strategic innovation and invention   Institution...");

        jmnuAdmin.setText("Administartion ");

        jmnuPaymnts.setText("Payroll Management");
        jmnuPaymnts.setToolTipText("Payroll and Pay slip");
        jmnuPaymnts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuPaymntsActionPerformed(evt);
            }
        });

        jmnuItemPaySlip.setText("Generate Pay slip");
        jmnuItemPaySlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payslipGenerator(evt);
            }
        });
        jmnuPaymnts.add(jmnuItemPaySlip);

        jMenuItemPayroll.setText("Generate Payroll");
        jmnuPaymnts.add(jMenuItemPayroll);

        jmnuAdmin.add(jmnuPaymnts);

        jMenu1.setText("View All Employees ");

        jmnuAllParmnt.setText("Parmenent Employees");
        jMenu1.add(jmnuAllParmnt);

        jmnuAllCntrct.setText("Contraced Employees");
        jMenu1.add(jmnuAllCntrct);

        jmnuAllCasual.setText("Casual Employees");
        jMenu1.add(jmnuAllCasual);

        jmnuAdmin.add(jMenu1);
        jmnuAdmin.add(jSeparator3);

        jmnuItemAddNewDept1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK));
        jmnuItemAddNewDept1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/PNG/Button Add-01.png"))); // NOI18N
        jmnuItemAddNewDept1.setText("Add New Department");
        jmnuItemAddNewDept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuItemAddNewDept1ActionPerformed(evt);
            }
        });
        jmnuAdmin.add(jmnuItemAddNewDept1);

        jmnuItemAddNewEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmnuItemAddNewEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/PNG/Folder Add-01.png"))); // NOI18N
        jmnuItemAddNewEmployee.setText("Add New Employee");
        jmnuItemAddNewEmployee.setToolTipText("Adds new employee");
        jmnuItemAddNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuItemAddNewEmployeeActionPerformed(evt);
            }
        });
        jmnuAdmin.add(jmnuItemAddNewEmployee);

        jmnuItemAddNewBankDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jmnuItemAddNewBankDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/PNG/Folder Blue-01.png"))); // NOI18N
        jmnuItemAddNewBankDetails.setText("Add New Employee Bank Details");
        jmnuItemAddNewBankDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuItemAddNewBankDetailsActionPerformed(evt);
            }
        });
        jmnuAdmin.add(jmnuItemAddNewBankDetails);
        jmnuAdmin.add(jSeparator4);

        jmnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmnuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/PNG/Button Close-01.png"))); // NOI18N
        jmnuExit.setText("Exit");
        jmnuExit.setToolTipText("Exits home ");
        jmnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuExitActionPerformed(evt);
            }
        });
        jmnuAdmin.add(jmnuExit);

        jMenuBarHome.add(jmnuAdmin);

        jmnuDepartment.setText("Departments");
        jmnuDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuDepartmentActionPerformed(evt);
            }
        });

        jMenuFinance.setText("Finance");

        jmnuFinParm.setText("Permanent Employees ");
        jMenuFinance.add(jmnuFinParm);

        jmnuFinContract.setText("Contracted Employees");
        jMenuFinance.add(jmnuFinContract);

        jmnuFinCasual.setText("Casual Employees");
        jMenuFinance.add(jmnuFinCasual);

        jmnuDepartment.add(jMenuFinance);

        jmnuHR.setText("Human Resource Department");
        jmnuDepartment.add(jmnuHR);

        jmnuExam.setText("Examinations And Academics");
        jmnuDepartment.add(jmnuExam);
        jmnuDepartment.add(jSeparator1);

        jmnuCit.setText("CIT Department");
        jmnuDepartment.add(jmnuCit);

        jmnuBEC.setText("Business and Economics");
        jmnuDepartment.add(jmnuBEC);

        jMenuBarHome.add(jmnuDepartment);

        jmnuNetTaxPerMonth.setText("Net Tax Per Month");
        jmnuTaxMgt.add(jmnuNetTaxPerMonth);

        jMenuBarHome.add(jmnuTaxMgt);

        jmnuHome.setText("Help");
        jmnuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuHomeActionPerformed(evt);
            }
        });

        jmnuHomeHelp.setText("Help");
        jmnuHomeHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuHomeHelpActionPerformed(evt);
            }
        });
        jmnuHome.add(jmnuHomeHelp);

        jMenuBarHome.add(jmnuHome);

        jInternalFrame1.setJMenuBar(jMenuBarHome);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 3992, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 3982, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(485, 485, 485)
                        .addComponent(jlblMotto)
                        .addGap(0, 3220, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(466, 466, 466)
                        .addComponent(jLabel1)
                        .addGap(0, 3217, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2968, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(68, 68, 68)
                .addComponent(jlblMotto)
                .addGap(302, 302, 302)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmnuDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuDepartmentActionPerformed
        //This code enables the viewing of all departments
        new PayrollDepartmentsDetails().setVisible(true);
       this.dispose();

    }//GEN-LAST:event_jmnuDepartmentActionPerformed

    private void jmnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuExitActionPerformed
        // This code exits the pyroll the payroll system
        new PayAdminLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmnuExitActionPerformed

    private void jmnuPaymntsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuPaymntsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmnuPaymntsActionPerformed

    private void jmnuItemAddNewDept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuItemAddNewDept1ActionPerformed
        //this code enable addition of new deepartment to the database.
        new PayrollDepartmentsDetails().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmnuItemAddNewDept1ActionPerformed

    private void jmnuItemAddNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuItemAddNewEmployeeActionPerformed
        // This code enble the addition of new employee to the database.
         new PayrollEmployeeDetails().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jmnuItemAddNewEmployeeActionPerformed

    private void jmnuItemAddNewBankDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuItemAddNewBankDetailsActionPerformed
        // adds new employee banks details
         new PaymentsBankForm().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jmnuItemAddNewBankDetailsActionPerformed

    private void jmnuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuHomeActionPerformed
        
    }//GEN-LAST:event_jmnuHomeActionPerformed

    private void jmnuHomeHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuHomeHelpActionPerformed
       //   provides context sensitive help
        new payrollHelp().setVisible(true);
    }//GEN-LAST:event_jmnuHomeHelpActionPerformed

    private void payslipGenerator(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payslipGenerator
        // TODO add your handling code here:
       
    }//GEN-LAST:event_payslipGenerator

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run()
            {
                new PayrollHome().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelTitleHome;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBarHome;
    private javax.swing.JMenu jMenuFinance;
    private javax.swing.JMenuItem jMenuItemPayroll;
    private javax.swing.JPanel jPanelDesignBar;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel jblLogo2;
    private javax.swing.JLabel jlblLogo;
    private javax.swing.JLabel jlblMotto;
    private javax.swing.JMenu jmnuAdmin;
    private javax.swing.JMenuItem jmnuAllCasual;
    private javax.swing.JMenuItem jmnuAllCntrct;
    private javax.swing.JMenuItem jmnuAllParmnt;
    private javax.swing.JMenuItem jmnuBEC;
    private javax.swing.JMenuItem jmnuCit;
    private javax.swing.JMenu jmnuDepartment;
    private javax.swing.JMenuItem jmnuExam;
    private javax.swing.JMenuItem jmnuExit;
    private javax.swing.JMenuItem jmnuFinCasual;
    private javax.swing.JMenuItem jmnuFinContract;
    private javax.swing.JMenuItem jmnuFinParm;
    private javax.swing.JMenuItem jmnuHR;
    private javax.swing.JMenu jmnuHome;
    private javax.swing.JMenuItem jmnuHomeHelp;
    private javax.swing.JMenuItem jmnuItemAddNewBankDetails;
    private javax.swing.JMenuItem jmnuItemAddNewDept1;
    private javax.swing.JMenuItem jmnuItemAddNewEmployee;
    private javax.swing.JMenuItem jmnuItemPaySlip;
    private javax.swing.JMenuItem jmnuNetTaxPerMonth;
    private javax.swing.JMenu jmnuPaymnts;
    private javax.swing.JMenu jmnuTaxMgt;
    // End of variables declaration//GEN-END:variables
}
